import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { IMetadata } from "../types";
import FormComponent from "../components/FormComponent";
import DisplayComponent from "../components/DisplayComponent";
import { useState, useEffect } from "react";
const Home: NextPage = () => {
  const [metaData, setMetaData] = useState<IMetadata>({})
  useEffect(() => {
    console.log(metaData)
  }, [metaData])

  return (
    <div>
      <Head>
        <title>NFT MetaTool🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <div className="bg-[#04111D] p-4 text-xl  text-slate-300">
          <span className="text-2xl">NFT MetaTool🚀</span>

        </div>
      </nav>
      {/* <div className="grid bg-[#202225] grid-cols-6 min-h-screen">
        <aside className="col-span-2"><FormComponent metaData={metaData} setMetaData={setMetaData} /></aside>
        <section className="col-span-4 text-white"></section>
      </div> */}
      <div className="bg-[#202225] min-h-screen">
        <DisplayComponent />
      </div>
    </div>
  );
};

export default Home;
